---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 01-nginx-ingress
  namespace: flux-system
spec:
  interval: 1m
  timeout: 3m
  path: "./k8s/apps/group-01/nginx-ingress/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: nginx-ingress
      namespace: nginx-ingress
    - apiVersion: apps/v1
      kind: Deployment
      name: nginx-ingress-default-backend
      namespace: nginx-ingress
  postBuild:
    substitute: { }
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
        optional: false
      - kind: Secret
        name: cluster-secrets
        optional: false
      - kind: Secret
        name: nginx-ingress-secrets
        optional: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 01-nginx-ingress-config
  namespace: flux-system
spec:
  interval: 1m
  timeout: 5m
  path: "./k8s/apps/group-01/nginx-ingress/config"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  dependsOn:
    - name: 01-nginx-ingress
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  healthChecks:
    - apiVersion: apps/v1
      kind: ConfigMap
      name: nginx-ingress-helm-chart-value-overrides
      namespace: nginx-ingress
  postBuild:
    substitute: { }
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
        optional: false
      - kind: Secret
        name: cluster-secrets
        optional: false
