---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: reloader
  namespace: reloader
spec:
  targetNamespace: reloader
  releaseName: reloader
  chart:
    spec:
      chart: reloader
      version: "v1.x.x"
      sourceRef:
        kind: HelmRepository
        name: reloader
        namespace: flux-system
  interval: 1m0s
  timeout: 3m0s
  values:
    installCRDs: true
  valuesFrom:
  - kind: ConfigMap
    name: reloader-helm-chart-value-overrides
    valuesKey: values.yaml
