---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cloudnative-pg
  namespace: cloudnative-pg
spec:
  releaseName: cloudnative-pg
  targetNamespace: cloudnative-pg
  chart:
    spec:
      chart: cloudnative-pg
      version: 0.17.1
      sourceRef:
        kind: HelmRepository
        name: cnpg-charts
        namespace: flux-system
  interval: 1m
  timeout: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: -1
    crds: CreateReplace
  values:
    installCRDs: true
  valuesFrom:
  - kind: ConfigMap
    name: cloudnative-pg-helm-chart-value-overrides
    valuesKey: values.yaml