---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: nginx-ingress
spec:
  releaseName: nginx-ingress
  interval: 1m
  timeout: 3m
  chart:
    spec:
      chart: nginx-ingress-controller
      version: 9.x.x
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  valuesFrom:
  - kind: ConfigMap
    name: nginx-ingress-helm-chart-value-overrides
    valuesKey: values.yaml # This is the default, but best to be explicit for clarity

