apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - repo.yaml
  - configmap.yaml
  - ../config/secrets.sops.yaml
  - helm-release.yaml
patchesStrategicMerge:
  - ../config/nginx-ingress-patch.yaml
