---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  chart:
    spec:
      chart: external-dns
      version: 6.x.x
      sourceRef:
        kind: HelmRepository
        name: bitnami-external-dns
        namespace: flux-system
  interval: 1m
  timeout: 5m
  releaseName: external-dns
  valuesFrom:
    - kind: ConfigMap
      name: external-dns-helm-chart-value-overrides
      valuesKey: values.yaml # This is the default, but best to be explicit for clarity
