---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - repo.yaml
  - ../config/configmap.yaml
  - ../config/external-dns.secrets.sops.yaml
  - helm-release.yaml
