---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: clickhouse
  namespace: flux-system
spec:
  interval: 5m
  type: oci
  url: oci://registry-1.docker.io/bitnamicharts
