---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer-roach
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-ca-roach
  namespace: cockroachdb
spec:
  isCA: true
  commonName: selfsigned-ca-roach
  secretName: selfsigned-ca-roach
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-issuer-roach
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: ca-issuer-roach
  namespace: cockroachdb
spec:
  ca:
    secretName: selfsigned-ca-roach