---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../app/client-secure.yaml
  - certificate-ca.yaml
  - configmap.yaml
  - zone-roach-CONFIG_INFRA_CLUSTER.CONFIG_INFRA_DOMAIN.yaml