---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 02-cockroachdb
  namespace: flux-system
spec:
  path: ./k8s/apps/group-02/cockroachdb/app/
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 1m
  retryInterval: 1m
  timeout: 3m
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substitute: { }
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
      - kind: Secret
        name: cluster-secrets
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 02-cockroachdb-config
  namespace: flux-system
spec:
  path: ./k8s/apps/group-02/cockroachdb/config/
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 1m
  retryInterval: 1m
  timeout: 1m
  wait: true
  dependsOn:
    - name: 02-cockroachdb
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substitute: { }
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
      - kind: Secret
        name: cluster-secrets
