---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: grafana-${CONFIG_INFRA_CLUSTER}.${CONFIG_INFRA_DOMAIN}
  namespace: external-dns
spec:
  endpoints:
    - dnsName: grafana-${CONFIG_INFRA_CLUSTER}.${CONFIG_INFRA_DOMAIN}
      recordTTL: 180
      recordType: CNAME
      targets:
        - ingress-${CONFIG_INFRA_CLUSTER}.${CONFIG_INFRA_DOMAIN}
      providerSpecific:
        - name: external-dns.alpha.kubernetes.io/cloudflare-proxied
          value: 'true'
