---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: ${CONFIG_INFRA_CLUSTER}.${CONFIG_INFRA_DOMAIN}
  namespace: external-dns
spec:
  endpoints:
    - dnsName: ${CONFIG_INFRA_CLUSTER}.${CONFIG_INFRA_DOMAIN}
      recordTTL: 180
      recordType: A
      targets:
        - ${CONFIG_K8S01_BGP_INTERNET_ADDRESS}
      providerSpecific:
        - name: external-dns.alpha.kubernetes.io/cloudflare-proxied
          value: 'false'
    - dnsName: ${CONFIG_INFRA_CLUSTER}.${CONFIG_INFRA_DOMAIN}
      recordTTL: 180
      recordType: AAAA
      targets:
        - ${CONFIG_K8S01_BGP_INTERNET_IPv6_ADDRESS}
      providerSpecific:
        - name: external-dns.alpha.kubernetes.io/cloudflare-proxied
          value: 'false'
    - dnsName: ingress.${CONFIG_INFRA_DOMAIN}
      recordTTL: 180
      recordType: A
      targets:
        - ${CONFIG_K8S01_BGP_INTERNET_ADDRESS}
      providerSpecific:
        - name: external-dns.alpha.kubernetes.io/cloudflare-proxied
          value: 'false'
    - dnsName: ingress-${CONFIG_INFRA_CLUSTER}.${CONFIG_INFRA_DOMAIN}
      recordTTL: 180
      recordType: A
      targets:
        - ${CONFIG_K8S01_BGP_INTERNET_ADDRESS}
      providerSpecific:
        - name: external-dns.alpha.kubernetes.io/cloudflare-proxied
          value: 'false'
    - dnsName: ingress.${CONFIG_INFRA_DOMAIN}
      recordTTL: 180
      recordType: AAAA
      targets:
        - ${CONFIG_K8S01_BGP_INTERNET_IPv6_ADDRESS}
      providerSpecific:
        - name: external-dns.alpha.kubernetes.io/cloudflare-proxied
          value: 'false'
    - dnsName: ingress-${CONFIG_INFRA_CLUSTER}.${CONFIG_INFRA_DOMAIN}
      recordTTL: 180
      recordType: AAAA
      targets:
        - ${CONFIG_K8S01_BGP_INTERNET_IPv6_ADDRESS}
      providerSpecific:
        - name: external-dns.alpha.kubernetes.io/cloudflare-proxied
          value: 'false'