---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 01-external-dns
  namespace: flux-system
spec:
  interval: 30m0s
  timeout: 5m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  prune: true
  path: ./k8s/apps/group-01/external-dns/app
###  healthChecks:
###    - apiVersion: apps/v1
###      kind: Deployment
###      name: external-dns
###      namespace: external-dns
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substitute: { }
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
      - kind: Secret
        name: cluster-secrets
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 01-external-dns-zones
  namespace: flux-system
spec:
  interval: 1m0s
  timeout: 3m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  prune: true
  path: ./k8s/apps/group-01/external-dns/zones
  dependsOn:
    - name: 01-external-dns
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substitute: { }
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
      - kind: Secret
        name: cluster-secrets
