---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-path
  labels:
    storage: local-path
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
#volumeBindingMode: Immediate