---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 00-local-path
  namespace: flux-system
spec:
  interval: 1m0s
  timeout: 15m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  prune: true
  path: ./k8s/apps/group-00/local-path/config

