apiVersion: v1
kind: Secret
metadata:
    name: basic-auth
    namespace: nginx-ingress
    annotations:
        kubed.appscode.com/sync: auth=basic-auth
type: Opaque
###
### Note this value is created by base64 encoding an htpassword file.
### eg. `htpasswd -nb user password | base64`
###
stringData:
    auth: ENC[AES256_GCM,data:9U9nqq4Hwnsczryl3ZwD7jmbLIMbXNLuKIzHRlHj+O+QzkMgBZG2lqz/a5gLZ6vptgVd0kfZuACl7e1orRF7fbYutUDmusjrzE4EqMESKdYvGDYTZUptKA==,iv:O9tpkWpIxUTdpHJYqsnWXL4q0qb2D5Qaw3g9OHXtxms=,tag:PaE3ubZ7/p/zqTsI8jqU/g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uh4xmxfre8wsglm3zmz765crc5y8qc42nklgfq8hlrhglunqyguqdcac6h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6RHZsenRVSXRVU0hCdjA1
            aDZwQUdjZnRQVzR4NG1lQnlhYzJETnJNU1VjCklJSHAzY0NueEpQN3RFcHovNVli
            dlBiY052dU42UXphRnhBYnFEYWVPMlkKLS0tIC95eFhDU2o0VEVYSnpDVlpzN01C
            eXh3R3pDalo2Y1V6VzA0dVZJMWt6VzgKj6TxIJ9KQlWgLlFE8QR9IWReifev3xoN
            PROh8oRBd+0r15suYLgSouSjlikoy1LKF9MvkcvbSaARV6tduLp5Ng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-01T05:47:42Z"
    mac: ENC[AES256_GCM,data:qn5sgejq/YxE8HVYDfm3Zj8x/KCwZ7Cr9V9oXEJrUwPRgqStAI4EKPDBb5M6SLOOYpXQCBkZ5LvspZ3aKm9GU4ooN4uyYZ1IdYO6Zvg40LMPszgQ3OW7877NAEGhqat38RoSsfaVpwuAIgbAk6TGRydn17wf3KB9RKFytZpyqpc=,iv:pK8RchzMeeYLKjui9cgywkmbXAUAGT0/kKDpXWpDW+s=,tag:LKr7emRg+2+C7xC0YRkrBw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
