---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cockroachdb
  namespace: cockroachdb
spec:
  releaseName: cockroachdb
  chart:
    spec:
      chart: cockroachdb
      version: 10.0.9
      sourceRef:
        kind: HelmRepository
        name: cockroachdb
        namespace: flux-system
  interval: 1m
  timeout: 5m
  valuesFrom:
  - kind: ConfigMap
    name: cockroachdb-helm-chart-value-overrides
    valuesKey: values.yaml # This is the default, but best to be explicit for clarity
