---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: config-syncer
  namespace: config-syncer
spec:
  chart:
    spec:
      chart: config-syncer
      version: v0.14.0-rc.0
      sourceRef:
        kind: HelmRepository
        name: config-syncer
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: config-syncer
  valuesFrom:
  - kind: ConfigMap
    name: config-syncer-helm-chart-value-overrides
    valuesKey: values.yaml # This is the default, but best to be explicit for clarity
