---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  targetNamespace: cert-manager
  releaseName: cert-manager
  chart:
    spec:
      chart: cert-manager
      version: "v1.11.0"
      sourceRef:
        kind: HelmRepository
        name: jetstack-cert-manager
        namespace: flux-system
  interval: 1m0s
  values:
    installCRDs: true
  valuesFrom:
  - kind: ConfigMap
    name: cert-manager-helm-chart-value-overrides
    valuesKey: values.yaml
    optional: true
