apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: superuser-secret
    namespace: cloudnative-pg
stringData:
    username: ENC[AES256_GCM,data:B47CgHvPwOw=,iv:jYChxSpB5P4QcaAgMsK1LIgn1D6bnzTPjgK3/IKFR8k=,tag:780g0Yk/qA/mwU+Cg2/oIQ==,type:str]
    password: ENC[AES256_GCM,data:pWBGabXYZDrHBqQ=,iv:pyTWLC954zfa33Ad/bIjHV17RSYMK4ZlP5nHkNi6k+Y=,tag:/THG2TR+LOj5Q/jjMmv+kQ==,type:str]
    secret: ENC[AES256_GCM,data:E9W7gWGeNi3ghaY=,iv:U219WFrGLosasIRpdCCc8xrPf16fTYKn7RrD0Jcc8Bo=,tag:mHBJ2tXzRn9y5s5PyWuU7A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uh4xmxfre8wsglm3zmz765crc5y8qc42nklgfq8hlrhglunqyguqdcac6h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCSCtqM0Jmb1ArYmd4SHhl
            aGxvc0dVUU1wbzdlRWZPLzNtWS9zQ0F6VnkwClFzVkVlMzh2eWtrcmFnMmdNakds
            YU5mS3RVNHZxY0FtV3UvUEpYMEdraVkKLS0tIG82UVpQckRrcG51S3ZzYmczR25s
            Nmh5MDV1dDdpVlA1R3JucEVBNURkSDAKCb7ycTzseQP0gogRIvvPcns99G17UOsU
            ohKgyoBhfkMjJtwf8a3IwaC4TDXuGrks6T7jcxQhs8GyKiLoIa5c1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-10T07:58:18Z"
    mac: ENC[AES256_GCM,data:WACdOTDA6C5EkROT8aa1+dK0bKwUESPL6B6qAeTfBVhEb0uPD0VdcWxL+aByAMEDec8PL+xSUCClio3WBpFqwHydMGQznAQdDLOj3t94U31OCKsOKuiivtCpha/fi1+SDpOtYbKfBjJaz5cvhXgtVQJ0m2K1jrUD1XLouyLs7+Y=,iv:lsYTluIHjg67f7Ra8IkiKTLGlKN1ObU+cZfspMLXcbY=,tag:/qGdL9zCbXBaaRnO6/3mXw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: ${CONFIG_KEYCLOAK_ADMIN}-secret
    namespace: cloudnative-pg
stringData:
    username: ENC[AES256_GCM,data:ZW/gKj/eCBY=,iv:7RgL7WfdK+HnIOojXkDc2fD76wFasFQbVrs6w8Jq7pg=,tag:4BNbegPNJff6KxQcdDWWRg==,type:str]
    password: ENC[AES256_GCM,data:eh5ctRAxDlkHybg=,iv:NxWmbY4qfreiO7XPPSJDS+D+ATxqpZfMKoILGaSeafM=,tag:mQgT5G24eD8MCGiuBv/hyw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uh4xmxfre8wsglm3zmz765crc5y8qc42nklgfq8hlrhglunqyguqdcac6h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCSCtqM0Jmb1ArYmd4SHhl
            aGxvc0dVUU1wbzdlRWZPLzNtWS9zQ0F6VnkwClFzVkVlMzh2eWtrcmFnMmdNakds
            YU5mS3RVNHZxY0FtV3UvUEpYMEdraVkKLS0tIG82UVpQckRrcG51S3ZzYmczR25s
            Nmh5MDV1dDdpVlA1R3JucEVBNURkSDAKCb7ycTzseQP0gogRIvvPcns99G17UOsU
            ohKgyoBhfkMjJtwf8a3IwaC4TDXuGrks6T7jcxQhs8GyKiLoIa5c1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-10T07:58:18Z"
    mac: ENC[AES256_GCM,data:WACdOTDA6C5EkROT8aa1+dK0bKwUESPL6B6qAeTfBVhEb0uPD0VdcWxL+aByAMEDec8PL+xSUCClio3WBpFqwHydMGQznAQdDLOj3t94U31OCKsOKuiivtCpha/fi1+SDpOtYbKfBjJaz5cvhXgtVQJ0m2K1jrUD1XLouyLs7+Y=,iv:lsYTluIHjg67f7Ra8IkiKTLGlKN1ObU+cZfspMLXcbY=,tag:/qGdL9zCbXBaaRnO6/3mXw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
