apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secrets
    namespace: external-dns
stringData:
    cloudflare_api_token: ENC[AES256_GCM,data:VaEAZkDPblvCn57HktfWveWvYPSdBfAwP8Le8ra7lk9j51FaflGJww==,iv:jUCDhIFqDMiJed6epP0L9bs/2WCLRMVHmtpnXNpru28=,tag:1WUykngLtU7JIGSENlGQyQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uh4xmxfre8wsglm3zmz765crc5y8qc42nklgfq8hlrhglunqyguqdcac6h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFMnlhbUp5QjV1Y2VhTjkw
            UXhNMTJ2NUxzd3dVeUxuMHVPcmd3Rnk4NXcwCnJOcXRmZmdOendsK2J6OXhva0JL
            TEN4VzRIY2xBZ3hwL2cwMVpTQmNEKzAKLS0tIFBDV0FjRGloT0dTWTgzUm0rWWVk
            djZteUswUEFpQzE0bzBFNWQ4UnFMbUUKsRk7vMmDceVBc6V5Zom1aoFz2A9Q/DLC
            b2gth8HUz6Smxl2sFO3AR78XGK01mEIwU2c7AjyDVl4Xta7caX4sdg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-01T03:06:50Z"
    mac: ENC[AES256_GCM,data:my3PojRVgsyZMcvh2K6QqepgNIbOpYwRQ+SbiqZfF0SgBR9KLYM8mQh4jRIc3DgVhx7HEaXSoG6U3TEU0sA58nuedxlf6PHNOafhiwBw9KVQH5MnmfQCiXMzy+m9szWh56Rbu/15DPcd8RvYl2CHDePIfYRvQzsvWsV50rVdM/g=,iv:WEyQJeeWdVgIoTgzzXJ/Mdfzu04Uplbmj2C3n5UgovE=,tag:DuRl1TDqLoDjRJpcHmGdsQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
